image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - hashicorp.terraform
    - ms-azuretools.vscode-docker
tasks:
  - name: Terraform
    command: |
      echo "Run Terraform Commands"
      terraform version